### ISSUE TITLE
Add Info section

### ISSUE THREAD

**Issue by sruti** [sruti/covid19-riskfactors-app#38]
I think we should add an info section before the legend that has a 1-2 line intro about what this app is and basic instructions on how to use it. Also change the title from 'COVID-19 Mortality' to something a bit more descriptive

**Comment by sylwiavargas** [comment]
**How about for title:** Covid-19 Mortality Risk Calculator

**For the description:** Use this app to assess severity or the development of acute respiratory distress syndrome (ARDS) of COVID patients. Choose the [WHAT] at the top. Below, you will see details on the study these results refer to. Underneath you can check the symptoms you notice in your patients to see their severity. Once checked, in the middle column you will see [WHAT IS THE MIDDLE COLUMN]. If the [SAME THING] features "ℹ️", you can click to tap on it to see [WHAT]. 

I think this should not be above. I think it should be a little icon "how to use this app" and once clicked, it will feature a modal. Otherwise, a mobile experience might be quite annoying. Or, it can be also a show/hide section.

**Comment by sruti** [comment]
Updated description from Tavish:
**Description:** This app is for medical practitioners to perform a basic assessment and risk calculation of a COVID-19 patient ending up in the ICU, developing acute respiratory distress syndrome (ARDS), and overall death. The data has been reviewed and compiled from studies published from patients in Wuhan.

**Disclaimer:** The data below is for informational purposes only. The objective is to provide an easier format to quickly review pertinent data. 

"ℹ️", you can click to tap on it to see statistical details.

**Comment by sruti** [comment]
We also want this section to be at the top (where the legend is currently) and put the notes and sources at the bottom (with clear demarcation about what and where it is)

**Comment by sruti** [comment]
And change the title to 'COVID-19 Risk Calculator'
